
version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - YANDEX_DISK_TOKEN=${YANDEX_DISK_TOKEN}
      - ALLOWED_USER_ID=${ALLOWED_USER_ID}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=INFO
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./temp:/app/temp

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
