[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["F401", "F841", "E402", "E722", "E741", "F541", "E701"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto" 